name: widget_factory
description: Flutter package providing factory abstract class for creating widgets.
version: 0.0.1+1
repository: https://github.com/Mol0ko/widget_factory

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
